name: my_radio
description: Private walkie-talkie and chat app using Flutter and Agora.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Библиотека для голосовой связи и передачи данных (чат)
  agora_rtc_engine: ^6.3.2
  
  # Библиотека для запроса разрешений (микрофон)
  permission_handler: ^11.3.1

  # Иконки (стандарт для Flutter)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Правила оформления кода
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true