name: Build APK
on: [push]

# Добавляем переменную, чтобы убрать предупреждение о Node.js
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Устанавливаем Java (нужна для сборки Android)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Если твои файлы лежат в подпапке, например 'helloworld', 
      # добавь в команды ниже: working-directory: helloworld
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Radio-Build
          path: build/app/outputs/flutter-apk/app-release.apk
